version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary tools"
      - curl -Lo /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 && chmod +x /usr/local/bin/hadolint
      - curl -Lo /usr/local/bin/kubelinter https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux && chmod +x /usr/local/bin/kubelinter
      - curl -sSL https://github.com/anchore/anchore-cli/releases/latest/download/anchore-cli-linux -o /usr/local/bin/anchore-cli && chmod +x /usr/local/bin/anchore-cli
      - curl -sSL https://raw.githubusercontent.com/zaproxy/zaproxy/main/scripts/zap.sh -o /usr/local/bin/zap && chmod +x /usr/local/bin/zap
      - yum install docker -y
      - sudo usermod -aG docker user
      - newgrp docker
      - yum install -y maven
      - yum install java-17 -y
  pre_build:
    commands:
      - docker login -u pradeep710 -p Nani@1999 
      - echo "Pulling SonarQube Docker image..."
      - docker pull sonarqube:10.6-community
      - echo "Starting SonarQube container..."
      - docker ps
      - docker run -d --name sonarqube -p 9000:9000 sonarqube:10.6-community
      - docker ps
      - echo "Waiting for SonarQube to be ready..."
      - echo "Installing SonarQube Scanner..."
      - curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
      - export PATH="/opt/sonar-scanner/bin:$PATH"
      - echo "Running SonarQube scan..."
      - mvn sonar-scanner -Dsonar.projectKey=nani-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -X || echo "SonarQube scan failed"
      - mvn clean compile
      - echo "Linting Dockerfile with Hadolint..."
      - hadolint Dockerfile || echo "Hadolint found issues"
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 970547349158.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo

  build:
    on-failure: ABORT
    commands:
      - #LINTING THE DOCKERFILE USING HADOLINT
      - echo "DOCKERFILE LINT STAGE"
      - docker run --rm -i hadolint/hadolint hadolint -f json - < Dockerfile || echo "Hadolint warnings detected"
      - echo Docker FILE LINT STAGE - PASSED   
      - docker build -t dev-sec-ops-repo .
      - docker tag dev-sec-ops-repo:latest $REPOSITORY_URI:latest
      - echo "Docker image built successfully."
      - echo "Pushing Docker image to ECR..."
      - docker push 970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo:latest
      - echo "Scanning Docker image with Anchore..."
      - export COMPOSE_INTERACTIVE_NO_CLI=1
      - curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -r $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "installing minikube..."
      - curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      - echo "installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - whoami
      - docker --version
      - echo "Starting Minikube as non-root user..."
      - minikube start --driver=docker --cpus=2 --memory=2200mb --disk-size=10g
      - kubectl config use-context minikube
      - kubectl cluster-info
      - minikube status
      - kubectl get nodes -o wide
      - echo "Updating Kubernetes deployment..."
      - sed -i "s|nginx|$REPOSITORY_URI:latest|g" deployment.yml
      - kubectl apply -f deployment.yml --validate=false
      - echo "Deployment successful!"
      - echo "Running Kubelinter on Kubernetes manifests"
      - kubelinter lint ./k8s --format json > kubelinter-results.json
      - echo "Saving Kubelinter results to S3"
      - aws s3 cp kubelinter-results.json s3://$S3_BUCKET_NAME/kubelinter-results.json
       - echo "Running OWASP ZAP for DAST"
      - zap -daemon -quickurl $TARGET_URL -quickout zap-results.json
      - echo "Saving OWASP ZAP results to S3"
      - aws s3 cp zap-results.json s3://$S3_BUCKET_NAME/zap-results.json

artifacts:
  files:
    - kubelinter-results.json
    - anchore-results.json
    - zap-results.json
 
   
