version: 0.2

env:
  variables:
    SONAR_HOST_URL: "http://172.19.41.165:9000/"
    SONAR_TOKEN: "squ_be3aeff8bfc16fe4c236c881557b775b28b2055a"
    AWS_REGION: "ap-south-1"
    REPOSITORY_URI: "970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo"
    CLUSTER_NAME: "dev-cluster"
    S3_BUCKET: "decsecops-bucket"

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing security tools..."
      - curl -Lo kubelinter.tar.gz https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz
      - tar -xzf kubelinter.tar.gz && mv kube-linter /usr/local/bin/
      - curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
      - chmod +x /usr/local/bin/hadolint
      - pip3 install awscli
      - curl -s https://ci-tools.anchore.io/quickstart.sh | bash -s -- -a
      - docker pull owasp/zap2docker-stable

  pre_build:
    commands:
      - echo "Running SonarQube SAST scan..."
      - sonar-scanner -Dsonar.projectKey=nani-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
      - echo "SonarQube scan completed."

      - echo "Linting Dockerfile with Hadolint..."
      - hadolint dockerfile || true
      - echo "Dockerfile linting completed."

      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 970547349158.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t dev-sec-ops .
      - docker tag dev-sec-ops-repo:latest 970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo:latest
      - echo "Docker image built successfully."

      - echo "Scanning Docker image with Anchore..."
      - anchore-cli image add $REPOSITORY_URI:latest
      - anchore-cli image wait $REPOSITORY_URI:latest
      - anchore-cli image vuln $REPOSITORY_URI:latest all || true
      - echo "Docker image scanning completed."

      - echo "Scanning Kubernetes Manifests with Kubelinter..."
      - kube-linter lint deployment.yml || true
      - echo "Kubernetes manifest scanning completed."

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Docker image pushed successfully."

      - echo "Updating Kubernetes deployment..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - sed -i "s|apache2|$REPOSITORY_URI:latest|g" deployment.yml
      - kubectl apply -f deployment.yml --validate=false
      - echo "Deployment successful!"

      - echo "Running OWASP ZAP DAST Scan..."
      - docker run --rm -v $(pwd):/zap/wrk:rw owasp/zap2docker-stable zap-baseline.py -t https://your-app-url.com -r zap-report.html || true
      - aws s3 cp zap-report.html s3://$S3_BUCKET/
      - echo "DAST scan completed and results uploaded to S3."

artifacts:
  files:
    - zap-report.html
    - imagedefinitions.json

