version: 0.2

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - yum install -y docker unzip
      - curl -Lo kubelinter.tar.gz https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz
      - tar -xzf kubelinter.tar.gz && mv kube-linter /usr/local/bin/
      - curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
      - chmod +x /usr/local/bin/hadolint
      - curl -I https://ci-tools.anchore.io/quickstart.sh || true
      - echo "Pulling SonarQube Docker image..."
      - docker pull sonarqube:10.6-community
      - docker login -u pradeep710 -p Nani@1999 || echo "Docker login failed"
      - echo "Pulling OWASP ZAP Docker image..."
      - docker pull zaproxy/zap-stable || echo "ZAP image pull failed"

  pre_build:
    commands:
      - echo "Starting SonarQube container..."
      - docker run -d --name sonarqube -p 9000:9000 sonarqube:10.6-community
      - echo "Waiting for SonarQube to be ready..."
      - sleep 30
      - echo "Installing SonarQube Scanner..."
      - curl -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
      - export PATH="/opt/sonar-scanner/bin:$PATH"
      - echo "Running SonarQube scan..."
      - sonar-scanner -Dsonar.projectKey=nani-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -X || echo "SonarQube scan failed"
      - echo "Linting Dockerfile with Hadolint..."
      - hadolint Dockerfile || echo "Hadolint found issues"
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 970547349158.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t dev-sec-ops-repo .
      - docker tag dev-sec-ops-repo:latest $REPOSITORY_URI:latest
      - echo "Docker image built successfully."
      - echo "Scanning Docker image with Anchore..."
      - anchore-cli image add $REPOSITORY_URI:latest || echo "Anchore image add failed"
      - anchore-cli image wait $REPOSITORY_URI:latest || echo "Anchore image wait failed"
      - anchore-cli image vuln $REPOSITORY_URI:latest all || echo "Anchore vulnerability scan failed"
      - echo "Scanning Kubernetes Manifests with Kubelinter..."
      - kube-linter lint deployment.yml || echo "Kubelinter found issues"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 970547349158.dkr.ecr.ap-south-1.amazonaws.com/dev-sec-ops-repo:latest
      - echo "Updating Kubernetes deployment..."
      - sed -i "s|apache2|$REPOSITORY_URI:latest|g" deployment.yml
      - kubectl apply -f deployment.yml --validate=false
      - echo "Deployment successful!"
      - echo "Running OWASP ZAP DAST Scan..."
      - docker run --rm -v $(pwd):/zap/wrk:rw zaproxy/zap-stable zap-baseline.py -t https://your-app-url.com -r zap-report.html || echo "ZAP scan failed"
      - aws s3 cp zap-report.html s3://$S3_BUCKET/
      - echo "DAST scan completed and results uploaded to S3."

artifacts:
  files:
    - zap-report.html
    - imagedefinitions.json
